### ISSUE TITLE
Api Client is not Connected Yet

### ISSUE THREAD

**Issue by ghost** [akashandroid90/GooglePlayServiceLocationSupport#3]
Many time when i open a activity which extends APPLOCATIONACTIVITY.
stucks and return google api client is not connected yet
Please help how to resolve

**Comment by akashjaindev** [comment]
Can you please provide me crash log you have. And i would like to know if this issue is device specific. And can you please tell me the way you are processing request.

**Comment by ghost** [comment]
I got the error in onenable update call there is Google Api Client is not connected

**Comment by akashjaindev** [comment]
Sorry i do not have any idea about it. Can you please provide detail for the same.

**Comment by akashjaindev** [comment]
Is your issue resolved?

**Comment by ghost** [comment]
Yes I have resolved that issue with editing in your APPLOCATION Class.
i update this line:
 if (enableUpdates && mGoogleApiClient != null && mGoogleApiClient.isConnected())
            LocationServices.FusedLocationApi.removeLocationUpdates(mGoogleApiClient, this);

**Comment by akashjaindev** [comment]
i have updated the library can you please check with latest build version
