### ISSUE TITLE
Make AppLocationActivity to extend AppCompatActivity

### ISSUE THREAD

**Issue by AruLNadhaN** [akashandroid90/GooglePlayServiceLocationSupport#4]
I can't use setSupportActionBar(toolbar); in my Activity. So please make AppLocationActivity to extend AppCompatActivity.

**Comment by akashjaindev** [comment]
Ok i will update today libray and let you know once it is done

**Comment by akashjaindev** [comment]
hello may i know which version you are using. as i can check library version 1.6 or the new one 1.7
